### ISSUE TITLE
Pay / Premium links

### ISSUE THREAD

**Issue by dawn-bethell** [WebSightArchitects/ABN#13]
Re: Pay Premium & Premium Funding see below:

These are exactly the same as Its Insured site if we can replicate those pages and link to them:

Pay Premium

http://www.itsinsured.com.au/payment.html

Premium Funding

On page 5 of  the copy document section 4) there is copy fpr premium funding can you just link to that section.

**Comment by aiwaam** [comment]
Those links has been done.

**Comment by dawn-bethell** [comment]
Checked
