### ISSUE TITLE
Sub Contents?

### ISSUE THREAD

**Issue by aiwaam** [WebSightArchitects/ABN#4]
There have several sub contents.
What do you prefer to show those sub content?

1. show all contents in one page and when the linked the screen scolled to the position.
2. hided first and then show with slide-down when click the link.
3. make all as a subpage and change the page when click the link.
4. any other suggest?

these are about the right side sub content links.
for e.g. Why use a broker? What is an insurance broker? and What is the difference? on the Main page.

Please let me know which method would be good.

**Comment by dawn-bethell** [comment]
@aiwaam - Sorry not sure what you mean? Can you send me a snapshot of what part you are referring to?
